menu:
  Home: /
  Archives: /archives
  ATOM: /atom.xml

widgets:
- search
- category
- tagcloud
- twitter

excerpt_link: Read More

twitter:
  username: boxersb
  show_replies: true
  tweet_count: 5

addthis:
  enable: true
  pubid: ra-525c9b3668ad1335
  facebook: true
  twitter: true
  google: true
  pinterest: false

fancybox: true

google_analytics: UA-39442592-1
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid: 123937814464693
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light